[build]
  base = "frontend"  # Set this to the folder containing your React app
  publish = "frontend/build"  # Output folder after running `npm run build` or `yarn build`
  command = "npm run build"  # Build command for React (can be `yarn build` if using Yarn)