[build]
  base = "frontend"  # Directory where Netlify runs the build command
  publish = "/dist"  # Correct output directory for Vite
  command = "CI= npm run build"  # Build command for React using Vite

[functions]
  directory = "frontend/netlify/functions"  # Directory where serverless functions are located
