[build]
  base = "frontend"  # Directory where Netlify runs the build command
  publish = "frontend/build"  # Correct output directory after build
  command = "CI= npm run build"  # Build command to generate the app

[functions]
  directory = "frontend/netlify/functions"  # Directory where serverless functions are located
